language: python
python:
  - "2.7"
cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - export DYLD_LIBRARY_PATH=$HOME/miniconda2/lib
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pytest pandas networkx libgfortran scikit-learn
  - pip install -r requirements-travis.txt
  - pip install .
script:
  - py.test tests
